### ISSUE TITLE
dictionary.json not found

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#113]
When pliers is installed "traditionally" (aka python setup.py install), it is unable to find 'dictionary.json' during imports.

e.g.:
`IOError: [Errno 2] No such file or directory: '/Users/alejandro/anaconda2/lib/python2.7/site-packages/pliers-0.0.1-py2.7.egg/pliers/datasets/dictionaries.json'`

Notably, when using `python setup.py develop` this does not happen, so that may be why you missed it. I'm guessing that install only copies over .py files, whereas develop makes symlinks to the folders, and thus the file can be found.

I had no luck googling this issue.

**Comment by tyarkoni** [comment]
Weird, I encountered this before and thought I fixed it. Will take a look. Thanks!
