### ISSUE TITLE
libmagic on windows

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#114]
Since ffmpeg does not run on Windows Ubuntu (due to subprocesses failing), I tried to run it on bare Windows.

libmagic on windows is difficult to install, and it's absence causes video conversion to fail. e.g.:

     FrameSamplingConverter().transform(video)

I found a project to compile libmagic dll's from scratch: https://github.com/nscaife/file-windows
Carefully running the build script line by line (to catch errors that require installing further dependencies, such as `autoconf`) resulted in the desired dlls. 

@tyarkoni to test that these dlls work I need you to copy them from `C:/Users/aid338/file_windows64` to `C:/Windows/System32`

**Comment by tyarkoni** [comment]
Is `video`  a string or a `VideoStim`?

**Comment by tyarkoni** [comment]
libmagic shouldn't be invoked unless you're passing strings in as stims (in which case it's called in order to try to figure out what the file in question is). If you initialize your `Stim` with something like `video = VideoStim('my_video.mp4')`, it should theoretically work without needing libmagic (and this is documented in the README I'm working on). If that's not the case, then I'll look into it some more.

**Comment by adelavega** [comment]
Ah, good to hear. I though it was a `VideoStim` but it's a string. Let me try

**Comment by adelavega** [comment]
Looks like its working now. Presumably ffmpeg should be hardware accelerated on the workstation so I hope this will take less time.

**Comment by tyarkoni** [comment]
When you initialize the `FrameSamplingConverter`, you need to pass in one of the arguments, otherwise you're sampling every single frame. I suggest something like `FrameSamplingConverter(hertz=2)` to start.

**Comment by tyarkoni** [comment]
I should probably set the default to something sensible, actually.

**Comment by adelavega** [comment]
I did that actually, just still takes a while. But looks like it worked and didnt' crash anything in Windows!

**Comment by adelavega** [comment]
FYI looks like it takes somewhere on the order of 30s per minute of video footage to run a ffmpeg converter (or at least this one). Way faster than on my mac that's for sure (where it just crashed).

**Comment by tyarkoni** [comment]
At what sampling rate? If it's at 2 Hz, that's not so good... and is this just the `FrameSamplingConverter` step, or are you chaining one or more extractors? It's the latter that should consume most of the time...

**Comment by adelavega** [comment]
Yep just `FrameSamplingConverter` at 2 Hz. I think it may have to do with the resolution of the movie because like I said it was excruciatingly slow/resource intensive on my mac. I can look into if this is being hardware accelerated. 

Does the extractor transform step require also require ffmpeg? I see its taking a while so I'm assuming so and that we may need to speed this up if that's the case.

**Comment by tyarkoni** [comment]
We're relying on MoviePy for the actual frame-reading (which I believe does depend on ffmpeg). In principle it should be pretty efficient, but it's possible pliers is fucking something up. I have some ideas about what might be going on, but won't have time to look into it until this evening.

**Comment by tyarkoni** [comment]
I looked into this and I don't think there's anything wrong. Extracting frames from .mkv-format movies as images seems to be pretty intensive compared to extracting them from mpeg containers, plus the video files from @mih are pretty high-res. I tested this out on a variety of movie files found [here](http://www.sample-videos.com/) and performance scales pretty much as you'd expect---it takes longer to do higher-res, longer movies, and certain formats.

I think a reasonable approach may be to first convert the .mkv files to .mp4, and only then run them through pliers. This probably won't save any time if you're just running it once, but it will save the most time-consuming step subsequently. Alternatively, if you're running in a notebook or ipython shell and expect to keep the `Stim`s in memory, you can set `config.cache_converters = True`, which will save you from having to do the conversion from `VideoStim` to `DerivedVideoStim` more than once.

**Comment by adelavega** [comment]
Cool thanks for digging in. That was my expectation as well. Video stuff just takes a while.

**Comment by adelavega** [comment]
Update: tried various codecs (mpeg1, mpeg2, h264 w/o b-frames), and all resulted in similar, if worse performance. I think without dropping the resolution this will stay about the same.
