### ISSUE TITLE
ExtractorResult.merge_stims() fails on GoogleVisionAPIExtractor results

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#115]
Looks like `merge_stims` expects each `ExtractorResult` to have a single stim, but GoogleVisionAPIExtractor has a single stim stored in a list of length 1. 

Thus, this line fails as it is not expecting a list, and a list does not have attribute "name"
https://github.com/tyarkoni/pliers/blob/master/pliers/extractors/base.py#L54

My guess is this issue arises here: https://github.com/tyarkoni/pliers/blob/master/pliers/extractors/google.py#L31

Because everywhere else in that object, multiple stims (from requests) are expected, but the whole list is stored int other `ExtractorResult`. 

Looks like it should be an easy fix but I'm not sure why there may be multiple requests to make the appropriate fix. In the mean time just merged results myself with `ExtractorResult.to_df(False)`

**Comment by tyarkoni** [comment]
Good catch. This is a classic case of premature optimization: we tried to make it so the API Extractors could batch-process Stims for the sake of efficiency, but now we get bitten in the ass when they try to hand the results of multiple requests back at the same time. Let me think a bit on what the right solution is; we don't want to just apply a band-aid, as the underlying principle of allowing multiple requests is something we probably want to abide by.
