### ISSUE TITLE
Fix prefix issue in Google Transformers

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#117]
Right now the Google API Transformers take a `handle_annotations` argument that can be either `'first'` or `'prefix'` (defaulting to the latter). The problem with this is that when there are multiple results returned, the column names get prepended with a prefix (e.g., `'face1_'`), but when there's only one result, there's no prepending. Consequently, when `merge_results` is called, there are mismatching column names and bad (or at least, confusing) things happen. The way to handle this is probably to split the `handle_annotations` argument into two, where `handle_annotations` now takes values of `'first'` or `'all'`, and we add a new boolean `prefix_first` argument that applies when `handle_annotations='first'`.

**Comment by qmac** [comment]
@tyarkoni Could we just prefix always, even when there's only one face? Doesn't seem that bad of a solution just might look a little weird in the output.

**Comment by tyarkoni** [comment]
Seems fine to me.
