### ISSUE TITLE
Add Stim class/hierarchy for remote resources

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#140]
Per @qmac's suggestion, we should have some way of representing remote resources that can be retrieved on-demand. We can detect file type fairly reliably from extension and/or mimetype info in the http header, but the actual file/contents should only be retrieved as-needed. It's unclear whether we want a single `RemoteStim` class that stores the data type internally as an attribute, a mixin that can be added to any existing `Stim` class, or some other solution.

**Comment by qmac** [comment]
Addressed (mostly) in #142
