### ISSUE TITLE
Should history, class, filename, etc. information exist in a single ExtractorResult?

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#164]
Currently, this information is only inserted when `merge_features` is called. However, it could be fairly useful for a user not using multiple extractors/the Graph interface to have this information appear when a single ExtractorResult is obtained.

**Comment by tyarkoni** [comment]
Agreed. Maybe we can have a `metadata` flag that excludes that info by default, but allows the user to retrieve it if they like.
