### ISSUE TITLE
Google web entities

### ISSUE THREAD

**Issue by andrewheusser** [tyarkoni/pliers#179]
I am using the Google Vision Web Entities API for a project, and I didn't see that supported in pliers.  I'd be happy to implement it and submit a pull request, unless its already implemented on another branch.  Let me know!

**Comment by tyarkoni** [comment]
I don't think it's supported (@qmac?), and a PR would be great, thanks! Let us know if you have any questions about implementation details--the existing `GoogleAPITransformer` transformer should make it fairly straightforward to add.

**Comment by qmac** [comment]
Can confirm it is not currently supported nor on another branch.

**Comment by qmac** [comment]
Closing thanks to #180
