### ISSUE TITLE
Stemming only works on last word

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#182]
Doubt this is the intended behavior, but when running the stem filter on a `TextStim` with more than one word, only the last word is stemmed.
Example:
```
>>> stim = TextStim(text='saying')
>>> filt.transform(stim).text
u'say'
>>> stim = TextStim(text='saying something')
>>> filt.transform(stim).text
u'saying someth'
```

**Comment by tyarkoni** [comment]
Good catch. I'm not actually sure what (if anything) to do about this. It's clearly not intended behavior, in the sense that no one in their right mind would want the output "saying someth" in the above example. On the other hand, this is arguably more a user problem than a software problem. I don't know that one should have the expectation that every token in an N-gram is automatically going to be individually stemmed.

Maybe the right way to handle this is to add a `tokenize=False` argument to the `WordStemmingFilter`. Then, if any value other than `False` is passed, the input `TextStim`'s text is first tokenized, then the stemmer is applied to each token, and then the resulting list is concatenated and returned. Other values could be `True`, in which case the default word tokenizer is used (from nltk perhaps), or a regex, in which case the regex is used to split the string.
