### ISSUE TITLE
PNG image not being loaded properly (incorrect data dimensions)

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#184]
Attempt to apply `BrightnessExtractor` (for example) fails on a .png image, but works fine on a .jpg. 
It seems to fail because the following operation is performed on the axis 2, and it is our of range:

            brightness = np.amax(data, 2).mean() / 255.0

It seems as though in the successful case, `stim.data` is 3 dimensional `(768, 1024, 3)` whereas it is only 2 dimensional `(400, 400)`

I imagine some differences between the files is causing the .png to be loaded incorrectly, perhaps because its black and white?

Bad stim:
![body01_lcm](https://user-images.githubusercontent.com/2774448/28739211-9f6ff03a-73be-11e7-98a0-ded0be4b6b0a.png)

**Comment by adelavega** [comment]
Looks like the culprit is `scipy.imread` and the image being black and white. The extra dimensions are only present for color images (perhaps varies by bits as well?). Probably best way to handle this is to add a b/w image to the test stimuli and see what fails.

**Comment by tyarkoni** [comment]
Yeah, there are no color channels for B&W images, and the extractor expects the third dimension. Should be an easy fix. Thanks!
