### ISSUE TITLE
Add new text dictionaries

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#19]
FeatureX has a [PredefinedDictionaryExtractor](https://github.com/tyarkoni/featureX/blob/master/featurex/extractors/text.py#L73) class that takes a block of text as input and returns values for each word. For example, via an affective norms database, one can get the valence and arousal of the words in one's text.

Adding new dictionaries is as simple as adding new JSON dictionaries to the [dictionaries.json](https://github.com/tyarkoni/pliers/blob/master/pliers/datasets/dictionaries.json) file bundled with the package. Any file added there can subsequently be used in the `PredefinedDictionaryExtractor`. Since there are potentially hundreds of usable and useful text feature dictionaries on the web, it would be great to expand the current list of supported resources.

**Comment by nullrejector** [comment]
dictionaries link: https://github.com/tyarkoni/pliers/blob/master/pliers/datasets/dictionaries.json

**Comment by tyarkoni** [comment]
Closing this; specific suggested dictionaries can go in #34.
