### ISSUE TITLE
support for clarifai v2

### ISSUE THREAD

**Issue by poldrack** [tyarkoni/pliers#197]
I am assuming that you are using the Clarifai V1 API since it asks for an ID and secret, whereas the V2 API seems to just provide an API key.  The site says that "As of November 15, 2017, we'll be shutting down our v1 API. " so if you are using V1 then it's going to stop working soon. if you are using V2 then can you be clearer about how the secret and ID map onto the API key?

**Comment by adelavega** [comment]
As far as I can tell we are.

Here's a transition guide: http://help.clarifai.com/api/transitioning-from-our-v1-to-our-v2-api

It also looks like they've added some new models: https://clarifai.com/models

**Comment by qmac** [comment]
Thanks for pointing this out! We actually are supporting v2+ after #181. The API does not seem to care if you use an old ID and secret or a new API key (looks like they accept either and there's not really a mapping, based on the python client code https://github.com/Clarifai/clarifai-python/blob/master/clarifai/rest/client.py#L3128). 

That being said, this issue should probably be reframed as adding support for passing an CLARIFAI_API_KEY to an extractor. Did not know they made this switch to API keys only.

**Comment by adelavega** [comment]
Hmm I wonder if they will ditch the id/secret when they drop support for v1? Maybe in that case we should drop support for id/secret
