### ISSUE TITLE
Add duecredit support

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#217]
It would be awesome to add [duecredit](https://github.com/duecredit/duecredit) support throughout the package, given that our extractors are coming from all kinds of places.

**Comment by qmac** [comment]
Where would we want the reference info to go? One central `.duecredit.p` summary file in the repo root? References put into each transformer docstring?

**Comment by tyarkoni** [comment]
No idea, TBH. I'm fine going with whatever other people seem to be doing. @yarikoptic, any thoughts on what might make sense for us? We have a lot of `Transformer` classes that should probably be individually decorated, but most link to URLs rather than papers.

**Comment by yarikoptic** [comment]
quick one
- `.duecredit.p` is not something to pre-create (it is created by duecredit while collecting the references)
- you can "cite" URLs as well (`Url` class, ), you could add those citations to specific methods of specific classes.  For generic examples, you could find them throughout pymvpa codebase (`git grep -A3 '\.dcite'`) 

Gimme an example class/reference and I would provide you a PR with duecredit support for it if it would be of help

**Comment by tyarkoni** [comment]
Thans @yarikoptic! A good example is the [SaliencyExtractor](https://github.com/tyarkoni/pliers/blob/master/pliers/extractors/image.py#L70). It wraps [PySaliencyMap](https://github.com/akisato-/pySaliencyMap), which I gather is an implementation of a method described in:

```[1] L. Itti, C. Koch, E. Niebur, A Model of Saliency-Based Visual Attention for Rapid Scene Analysis, IEEE Transactions on Pattern Analysis and Machine Intelligence, Vol. 20, No. 11, pp. 1254-1259, Nov 1998.
```

So ideally, we would want to provide all of this information: a link to the toolbox we're wrapping, and also a citation to the method. What would that look like?
