### ISSUE TITLE
Rethinking generators

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#221]
In constructing examples for the new docs, I'm coming to the conclusion that our use of generators instead of lists is kind of a UI nightmare. It's pretty much impossible for a naive user (or even me in some cases) to know what kind of iterable they're getting back, which makes inspection of the resulting objects much more cumbersome than it should be. Basically, unless you're planning to go all the way to a pandas `DataFrame` with pliers code (e.g, in a `Graph`), things get hairy pretty quickly.

It's clearly not an optimal solution to just return lists everywhere, since almost anything meaningful one might want to do with, e.g., a large movie, could potentially result in crazy memory use (and this was what prompted me to use generators in the first place). But I think that's at least an easily understandable problem from the user's perspective--i.e., it wouldn't take much for a user to write an outer loop around `VideoFrameStim`s and save the results to file in batches.

Perhaps the right approach is to build batching--and possibly file-writing--functionality into the `Graph`. That way, when users initialize a `Graph`, they just have to specify a batch size, file store, etc. We could potentially use HDF5 to store intermediate results if needed.

In any case, I don't think we should hold up the former change (dropping generators, at least by default) until we have a scheme along the latter lines figured out. We should probably make it a high priority to just use lists for now (and maybe have a config setting that enables them if the user really knows what they're doing).

**Comment by tyarkoni** [comment]
After tinkering a bit, an elegant solution to this problem that requires almost no changes to the code is to keep using generators throughout the core logic (as we currently do), but wrap the to-be-returned iterable (i.e., from the `transform()` call) in a function that checks against a `config.use_generators` boolean. If generators are off (which will be the default now), any generators are recursively converted to lists. Otherwise they're preserved as generators. So basically, we keep using generators internally, but convert them to lists on output, unless the user indicates they want to keep using generators.

Since I've already refactored a bunch of the code as I work up new docs, I'll just integrate this into the forthcoming PR--unless you have any objections, @qmac.

**Comment by qmac** [comment]
This sounds good to me. Is the not knowing if a generator or list is being returned only a product of some of the `BatchTransformerMixin` code (https://github.com/tyarkoni/pliers/blob/master/pliers/transformers.py#L177)? There might be an easy way to fix that but I'd need to look into it more. Either way, the idea of making it a config setting and forcing the returned type sounds good.

**Comment by tyarkoni** [comment]
From a naive user perspective, the main problem I see is that generators will be returned any time iteration is involved--and that can violate expectations in odd ways. Consider these two calls:

```python
res1 = converter.transform(stim)
res1 = converter.transform([stim])
```
Out of the box in pliers, the first call returns another `Stim` instance, while the second returns `[<generator>]`. I think this is *really* unintuitive for naive users (and probably also for many non-naive users). But I don't see any good way to avoid it so long as we want to use generators internally. So probably best to default to always returning lists, while still allowing power users to unmask the generator usage that's already going on under the hood.

**Comment by qmac** [comment]
@tyarkoni satisfied to close this after #228?

**Comment by tyarkoni** [comment]
Yep!
