### ISSUE TITLE
Package-wide handling of multiple results from a single Stim

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#227]
It's not uncommon for an `Extractor` to return multiple results for a single `Stim`. For example, there can be multiple faces detected for a single `ImageStim`, which means we then need to somehow represent multiple sets of variables within the same `ExtractorResult`.

This already came up in #77, but I think it's worth reconsidering the solution we settled on in #100--especially in light of discussion in #223 about moving formatting options into the individual `Extractor` classes. In general, I'm not really happy with the current solution of repeating all columns and appending them with suffixes (e.g., 'upper_left_face1', 'upper_left_face2', etc.). I think it often results in huge, unwieldy tables--especially when combined with other results from heterogeneous `Stim` types via `merge_results`.

I think it would be nice to have a package-wide config setting called something like `handle_multiple_results` that provides a variety of options for displaying multiple results. Rather than appending suffixes and repeating columns, I lean towards having the default be to create lists or tuples that contain all of the results. So then instead of having two values like `upper_left_face1=475` and `upper_left_face2=360`, we would would have `upper_left=(475, 360)`. This might create a little more work for users on the parsing side, but it would look much cleaner. We could still provide most/all of the options implemented in the `handle_annotations` argument to the Google extractors (e.g., 'repeat', 'concatenate', 'first', etc.).

One additional benefit of doing it this way is we could pass the result of each `Extractor`'s `to_df` method to the base class's `to_df`, where the reformatting could be done seamlessly, so long as the `Extractor` follows some naming convention. For example, we could mandate that developers have to create a `DataFrame` with multiple repeating sets of columns with numbered suffixes (just like the current handling), and so long as that was respected, end users would get the ability to reformat results for free using any of the above options.

**Comment by tyarkoni** [comment]
Any thoughts, @qmac?

**Comment by qmac** [comment]
Don't feel strongly towards one way or the other, not sure if this will solve the problem of unwieldy tables. Worth to experiment making it configurable.
