### ISSUE TITLE
Default to long-format data when merging ExtractorResults

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#230]
I don't remember what the original rationale was for returning data from `merge_results` in wide format, but in practice, this becomes kind of unmanageable with heterogeneous extractors because we end up with hundreds of columns and mostly NaN values. I'm thinking of changing the default to long format (with an option to return wide). Any objections, @qmac?

**Comment by qmac** [comment]
I think that wide format is the more intuitive default and more in line with normal (non-multimodal) feature extraction. Moreover, if this is suggesting we just do so when merging then we have a format incongruence between single and merged results. What about defaulting wide and option to return long?

**Comment by tyarkoni** [comment]
That would make sense from a backward compatibility standpoint... but wide is just hideously ugly in most cases because of the sparse nature of the data. And when there are a lot of rows, the resulting tables can be difficult to load/inspect.

The other issue that's addressed more naturally by long format is what to do when there are multiple results for a single `Stim` (cf. #227). In long format, it's pretty easy to add a column like "object_id". In wide format, barring the solution discussed in #227, we often end up with a monstrous number of columns.

Anyway, I'm in the process of reimplementing a lot of the results-generation code, and we can evaluate it both ways once that's done. It turns out that, regardless of what we end up returning to the user by default, it's much easier to construct the initial `DataFrame` in long than wide (a lot of the alignment/merging issues go away). So I'm going to set it up that way internally, and then we can pivot to wide.

**Comment by qmac** [comment]
So, for clarification, would calling `to_df` on a single `ExtractorResult` (no merging) produce a long format `DataFrame`?

**Comment by tyarkoni** [comment]
I think it would probably make sense for `to_df` to return data in the same format by default, whether merged or not. That leaves open whether it returns in wide or long. We will definitely want to have the `format` option available for both calls (with the same semantics).

**Comment by qmac** [comment]
Ok, then my only objection is lack of intuitiveness for the uni-modal use case. I think wide is certainly more readable when the features aren't sparse. However, definitely makes sense for our uses with many extractors/features and modalities.
