### ISSUE TITLE
IBMSpeechAPIConverter not listed among Extractors

### ISSUE THREAD

**Issue by rogilmore** [tyarkoni/pliers#231]
See: https://github.com/tyarkoni/pliers/blob/master/pliers/extractors/__init__.py

This, `from pliers.extractors import IBMSpeechAPIConverter`

accordingly yields

`ImportError: cannot import name 'IBMSpeechAPIConverter'`

**Comment by qmac** [comment]
The `IBMSpeechAPIConverter` is one of the `Converter`s, which convert between stimuli types (in this case Audio to Text). It could be successfully imported using:

`from pliers.converters import IBMSpeechAPIConverter`

Was there a point in the README or documentation that listed the `IBMSpeechAPIConverter` as an `Extractor`?
More information on [the different types of transformers](http://tyarkoni.github.io/pliers/basic-concepts.html#types-of-transformers)

**Comment by rogilmore** [comment]
​Sorry. My mistake. I did not see the section on the README page where this
is an extractor.​

**Comment by tyarkoni** [comment]
@rogilmore sorry, the README isn't in great shape. A new release, including updated README, is coming very shortly. In the meantime, there are more comprehensive docs [here](http://tyarkoni.github.io/pliers/) (including a comprehensive list of all Transformers).
