### ISSUE TITLE
Avoid exists calls to work with DataLad

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#236]
`DataLad` `AutomagicIO` monkey patches `open` to allow it to unlock and get files if they are not locally available prior to opening. But, in places where `exists` is called first (e.g. `load_stims`), DataLad won't have a chance to load the file, as `exists` is not monkey patched.

Note they are considering monkey patching `exists`, but I wanted to open this here as it may be an easy fix for my situation to simply try opening files, and catching a `FileNotFoundError`.

**Comment by qmac** [comment]
Linking discussion on https://github.com/datalad/datalad/issues/1924

**Comment by adelavega** [comment]
The update is that Datalad 0.9.x will support `exists` and `isfile`; but only the latter triggers downloading the file. In addition, `libmagic` needs `realpath` once the file is downloaded to get the correct mimetype. I think I can patch this soon as using those two calls should also work with regular files.

**Comment by qmac** [comment]
Closing after #253.
