### ISSUE TITLE
Simplified Graph API for linear chains of transformers

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#249]
Currently, it is quite cumbersome to add linear chains to a graph (requires many nested tuples/arrays or JSON objects).

One proposal is to include this functionality as another method of `Graph` such as `add_chain` that adds a list of transformers passed to be executed in sequence.

Another potential approach is to extend the functionality of the `add_nodes` method to allow for adding nodes both vertically (linear chain) or horizontally (branching).

**Comment by tyarkoni** [comment]
I like both: add an argument to `add_nodes` that can be set to `horizontal` (default) or `vertical`. Then `add_chain` can be an alias for `add_nodes(..., mode='vertical')`, and `add_children` can be an alias for `add_nodes(..., mode='horizontal')`.
