### ISSUE TITLE
Add paid keys for Microsoft APIs to travis

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#258]
I added some temporary keys to travis under `MICROSOFT_FACE_SUBSCRIPTION_KEY`, `MICROSOFT_VISION_SUBSCRIPTION_KEY`, and `MICROSOFT_SUBSCRIPTION_LOCATION`, but these will expire in ~20 days. 

Would be nice to have permanent keys in travis so the tests don't end up failing. Ideally #237 should be addressed as well since this would also incur cost.

Keys can be retrieved from https://azure.microsoft.com/en-us/try/cognitive-services/ and clicking "Get API key" for the Face and Vision APIs (one for each). The location for the keys will also need to be set as a env variable.

**Comment by tyarkoni** [comment]
Cool, will do right now. Do you foresee needing keys for any other services, or just face and vision? If there will be others, I may as well add them now too.

**Comment by qmac** [comment]
Maybe also the TextAnalytics API and the Bing Speech API (speech-to-text). The Emotion, VideoIndexer, and SpeakerID APIs are still in "Preview" so not sure about those.

**Comment by tyarkoni** [comment]
What should `MICROSOFT_SUBSCRIPTION_LOCATION` be set to? I'm not seeing info about that anywhere.

**Comment by qmac** [comment]
It should be at the start of the Endpoint URL. If its the same as mine it should be `westcentralus`

**Comment by tyarkoni** [comment]
Okay, those are all added. The names for the unimplemented ones are `MICROSOFT_BING_SPEECH_SUBSCRIPTION_KEY` and `MICROSOFT_TEXT_ANALYTICS_SUBSCRIPTION_KEY`.
