### ISSUE TITLE
Remove dependence on speech_recognition for Wit

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#268]
Although `speech_recognition` was initially very useful, its somewhat unnecessary now that the Wit API is the only converter using it. In addition, its stuck using a 2016 version of the API.

**Comment by tyarkoni** [comment]
Alternatively, we could leave it in and add a generic `SpeechRecognitionAPIConverter` class if that's possible given the `speech_recognition` architecture.

**Comment by qmac** [comment]
Hesitant to close this issue because I still don't love being stuck at the 2016 version of the API. I have a sneaking suspicion this is causing the occasional "Bad request" errors on Wit tests.

**Comment by qmac** [comment]
Closing for now, hopefully speech_recognition [gets updated soon](https://github.com/Uberi/speech_recognition/pull/344).
