### ISSUE TITLE
Rate limits for API transformers

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#271]
Some commercial APIs (e.g., Microsoft Cognitive Services) have rate limits for free APIs. This means pliers transformations will often result in exceptions even if the user is well under the monthly usage limit for their free tier. To accommodate this, we probably need to add rate-limiting functionality to any transformer making requests.

Now that we have the `APITransformer` class, that's a natural place for this to go. We could probably just keep an internal timer (e.g., `_last_request_time`) that gets reset on every call, and have the `_transform` call go to sleep as needed. We can add an instance variable for the rate limit that by default is set to the class-level default (which will be determined by the service). E.g., for the Microsoft services, we would have `_rate_limit = 3` (20 requests / minute), but the user could pass `rate_limit=10` as an argument if they wanted something else.

**Comment by tyarkoni** [comment]
Marking this as high priority since tests will continue to fail for Microsoft services until we implement it.

**Comment by qmac** [comment]
This seems fairly simple to implement at first glance, so I will try to include it in #270 before merging.
