### ISSUE TITLE
Add ability to dynamically set features, onsets, durations, orders in ExtractorResults

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#277]
Currently any ExtractorResult constructed from `raw` and expecting `to_df` to be called will hold `None` in the `features` `onset` `duration`, and `order` fields after construction.

The latter three are not a particular issue at the moment, since they will be propagated from the `stim` during transformation. However, if `to_df` created multiple feature events, this would be an issue.

Similarly, `features` will always be `None`, and the expected behavior would be that it matches the output of the `data` property.

**Comment by qmac** [comment]
The solution will probably require either a) computing a `to_df` call on init to load some reasonable defaults or b) making each into a property and computing a `to_df` call in each property access

**Comment by tyarkoni** [comment]
I think (a) is likely to be less expensive (and will probably also require less code), as it at most involves one extra `to_df` call each time.

**Comment by qmac** [comment]
@tyarkoni @adelavega Given the changes from #281, how should we deal with the situation when `_to_df` gives back a legitimate (not features) `onsets` column? We could check if the `onset` property has been set for the `ExtractorResult` object and override if `None` (if `_to_df` is being called there probably weren't preset onsets), but is there something more elegant?

**Comment by tyarkoni** [comment]
What's the problem with having an `onsets` column in the returned DF?

**Comment by qmac** [comment]
We wouldn't be 100% certain if they were feature names or real `onsets`. Also, as implemented after #281, it'd just get renamed to `'onsets_'`.

**Comment by qmac** [comment]
Just using `onsets` as an example, would apply to the other timing columns

**Comment by tyarkoni** [comment]
Isn't the timing column named `onset`, singular? If you mean that `onset` (timing) could be easily confused with `onsets` (feature), I agree that it could, but I would probably want to file that under "user's problem"...

**Comment by qmac** [comment]
Oh yea, I meant to say `onset`, singular, in all of my comments

**Comment by tyarkoni** [comment]
If I'm reading it correctly, the column renaming happens before the insertion of timing columns, so I don't think there can ever be any ambiguity. The worst case scenario is that a DF contains both `'onset'` and `'onset_'` columns, which is admittedly confusing, but again, I incline to treat this as the user's problem. What the API (and documentation) should guarantee is that asking for `.onset` will *always* return timing information. From that, one should infer that if a feature was originally named 'onset', it will not be so named in the DF.

**Comment by qmac** [comment]
Yeah, I'm saying that if the `Extractor`'s `_to_df` call wants to manually return timing information that is different from that of the `ExtractorResult` (e.g. in video extraction), then we will incorrectly interpret that as a feature and not the corrected timing information.

**Comment by tyarkoni** [comment]
Ahhh, now I get it. Good point. I don't think this is a naming issue per se though, because as it stands right now, if a subclassed `to_df` call adds timing columns, they'll actually be overwritten in the parent method, independently of the name conflict resolution. So I think we need to figure out a generic way to indicate that timing columns have already been set. It's a bit hacky, but we could adopt a convention  of prepending columns with `_`, so that if `_onset` exists, it's renamed to `onset` and the onset injection that would otherwise happen is skipped. There may be a better solution...

**Comment by adelavega** [comment]
I think its just an inherent problem with wide format dfs. Are there other keys that would have a similar problem? 

I suppose another solution is to return in long format which would avoid ambiguity more generally, but it would require reworking `to_df` and checking for conflicting columns before casting back to wide.
