### ISSUE TITLE
GoogleVisionAPILabelExtractor to_df fails when result empty

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#278]
Although rare, Google will occasionally return no labels for certain images, like this one (oddly enough):
https://github.com/tyarkoni/pliers/blob/master/pliers/tests/data/image/CC0/4416537561_27d7083571_z.jpg

In that scenario, the raw result will be `[{}]` and the follwing line `to_df` will fail:

    res = {label['description']: label['score'] for label in result._data}

I can fix this one, but I do find it weird this image would return an empty response (I tested others and it seems fine)

**Comment by qmac** [comment]
Yeah, this was fixed in 8b7f193, so pending merge of #270.

**Comment by adelavega** [comment]
Cool
