### ISSUE TITLE
Transformations on file paths not caching

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#284]
Because of the `isinstance(stim, Stim)` check in the memoization code, transformations on file paths (strings) are not caching. This is because memoization wraps `.transform` but the file path is converted into a `Stim` within `.transform`. The fix may be as easy as adding something like `or isinstance(stim, string_types)`.

**Comment by tyarkoni** [comment]
Makes sense. `isinstance` takes a tuple as the second arg, so `isinstance(stim, (Stim, string_types))` should take care of it.
