### ISSUE TITLE
get_frame using onset on a sampled VideoFrameCollection IndexError

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#298]
https://github.com/tyarkoni/pliers/blob/master/pliers/stimuli/video.py#L102 finds the frame number, not the index.

**Comment by tyarkoni** [comment]
Aren't they the same thing? Or do you mean because the cljp could in theory be cropped, etc.?

**Comment by qmac** [comment]
`index` was meant to refer to the location in the `frame_index`, which contains the corresponding `frame_num`. They differ if the `frame_index` has been sampled via a `FrameSamplingFilter`

**Comment by qmac** [comment]
I'm not entirely sure the best way to go about solving this. Currently, we model a sampled `VideoFrameCollectionStim` as a sequence of frames from the original video, such that the duration of the entire stim is just (number of sampled frames / video fps) and each frame has a duration of (1 / video fps) and retains its onset from the original video. This means that the onset of a sampled frame can be beyond the sampled stim's full duration. @tyarkoni approve of this approach?

Relating to this issue: it becomes ambiguous to get the frame at a particular onset (assuming its an onset relative to the original video). We'd could (1) search through the sampled stim's `frame_index` and look for the closest frame. Alternatively, though less consistent with the design, we could (2) interpret the requested onset as being relative to the sampled stim's timecourse. Or we could (3) ignore/warn/raise when `onset` is passed to `get_frame` on a sampled `VideoFrameCollectionStim`.

I'm leaning towards (1) but just wanted some thoughts/ways to make this all less ugly.

**Comment by qmac** [comment]
(2) is a simple solution since we could only make the `onset` parameter available in the `VideoStim` subclass.

**Comment by tyarkoni** [comment]
I like (2) but I'm thinking we should maybe also change the name of `get_frame` so that it's less ambiguous and different from the `VideoStim` method. Maybe `get_frame_at_index`?

**Comment by tyarkoni** [comment]
...and to finish the thought, maybe we split `get_frame` (which probably takes too many arguments anyway) into `get_frame_at_index` and `get_frame_at_onset`, with the latter only implemented in `VideoStim`, and the former in both.

**Comment by tyarkoni** [comment]
I suppose we could keep `get_frame` as a wrapper for backward compatibility, and just have it raise an exception if the user tries to get a frame by onset from a `VideoFrameCollection`.

**Comment by qmac** [comment]
Sounds good, though I kind of like a single `get_frame` method. Compromise with `get_frame_at_index` in the base `VideoFrameCollectionStim` and `get_frame` wrapper in `VideoStim`?

**Comment by qmac** [comment]
Actually scratch that, the duration of each `VideoFrameStim` is currently the onset distance between it and the next frame in the frame collection (not 1/fps in the case of a sampled stim)

**Comment by tyarkoni** [comment]
I like `get_frame` too in theory, I just don't like the idea of the default behavior being quite different in the two cases. As long as it's as clear as possible to the user what's going on, I don't really care what the methods are called.

**Comment by qmac** [comment]
As a side note, I think it's also best to make the `VideoFrameCollectionStim` duration be the original video's duration to be consistent with the timing of the contained frames. Only reason I changed it originally was to make it work for `long_jobs` (from the `allow_large_jobs` config option)
