### ISSUE TITLE
Some ideas to add music based feature extraction using music information retrieval tools

### ISSUE THREAD

**Issue by ejolly** [tyarkoni/pliers#30]
Here are some examples:

https://github.com/jsawruk/pymir

http://www.ifs.tuwien.ac.at/~schindler/lectures/MIR_Feature_Extraction.html

**Comment by ljchang** [comment]
Nice Jupyter notebooks for MIR http://musicinformationretrieval.com/

**Comment by ljchang** [comment]
https://github.com/craffel/mir_eval

**Comment by ljchang** [comment]
https://github.com/librosa/librosa

**Comment by ljchang** [comment]
[gist for A-weighting] (https://gist.github.com/endolith/148112#file-a_weighting-py)

**Comment by qmac** [comment]
@tyarkoni If comfortable, we can probably close this after #190, maybe moving the other libraries/techniques to #34.

**Comment by tyarkoni** [comment]
Agreed--closing this and adding to #34.
