### ISSUE TITLE
object_id missing when argument set to 'auto'

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#305]
From `pliers/extractors/base.py` L149:
```
if object_id is True or (object_id == 'auto' and len(set(index)) > 1):
```
The second clause with 'auto' isn't actually checking whether or not the resulting column will be constant. I believe something along the lines of
```
if object_id is True or (object_id == 'auto' and len(set(index)) < len(df)):
```
would produce the desired behavior.

**Comment by tyarkoni** [comment]
Proposed fix looks good to me.
