### ISSUE TITLE
Loading videos: Audio FPS can be unknown

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#311]
When loading a video, an error occurs due to this line:

https://github.com/tyarkoni/pliers/blob/cfd43d4143fd8a3b148cf12c23996128b671d428/pliers/stimuli/video.py#L82

audio_fps is return as `unknown`,  and that value later causes `moviepy` to throw an error, because it is expecting a float, not string.

seems as though ffmpeg is returning `unknown` for some reason, and previously this wasn't a problem because the `audio_fps` was previously not passed down in the same manner. 

I think the easy solution here is to treat `unknown` as None, and set to the default value of `44100`

**Comment by qmac** [comment]
Could you send me the culprit stim? I'm curious since this may be caused by my moviepy fix from earlier 😕. 
https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L391 is the responsible snippet.

**Comment by adelavega** [comment]
Here's the offending video: https://www.dropbox.com/s/pz3qycu4lsyprxj/life_2.mkv?dl=0

**Comment by qmac** [comment]
Weird, I was not able to recreate the 'unknown'

**Comment by adelavega** [comment]
It's possible its an ffmpeg version issue
