### ISSUE TITLE
S3 bucket instead of local file for text extractor

### ISSUE THREAD

**Issue by debanjanghosh** [tyarkoni/pliers#314]
Hi,
I am looking at the "TextEmbeddingExtractor" class (text.py file) and observe that the constructor takes the name of the embedding file as a parameter. I was wondering whether Pliers already support any API that allows to load a S3 bucket, say an embedding file hosted on AWS without downloading (i.e., probably by using boto3). Please let me know.
Best!

**Comment by qmac** [comment]
The `TextEmbeddingExtractor` does not have any support for remote embedding files. This is not on the road map to implement as we do not know of any APIs that allow that (let us know if you find one).

Currently, any `Stim` can be initialized from a public URL, including signed S3 URLs, but we will likely not support anything beyond this.
