### ISSUE TITLE
transformers for ExtractorResult objects

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#317]
To complement the current set of transformers (i.e., Extractors, Converters, and Filters), it would be useful to add a hierarchy of post-extraction transformers (maybe called `PostProcessor`) that takes an `ExtractorResult` as input and returns a transformed instance of the same class. This would accommodate things like `DummyCodingPostProcessor`, which could convert all extracted string features to groups of binary indicators.

**Comment by adelavega** [comment]
This was addressed by #394
