### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#323]
It's about that time. We don't need to actively do anything other than drop mention of Python 2 from the docs and remove Py2 from the travis matrix. Then we can just remove Python 2-specific features as we come along them.

**Comment by qmac** [comment]
Lingering: use of `contextlib2`

**Comment by tyarkoni** [comment]
Yeah, there are lots of Py2 features still having around. I closed this to reflect the fact we no longer officially support/test 2; anything that doesn't actively break on 3 can be removed at our leisure (probably as people work on related code).
