### ISSUE TITLE
ImageIO/Pillow unexpected keyword "pilmode"

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#331]
```
self = <imageio.plugins.pillow.JPEGFormat.Reader object at 0x7f9796f86630>
format = <Format JPEG-PIL - JPEG (ISO 10918)>
request = <imageio.core.request.Request object at 0x7f9796f865c0>
    def __init__(self, format, request):
        self.__closed = False
        self._BaseReaderWriter_last_index = -1
        self._format = format
        self._request = request
        # Open the reader/writer
>       self._open(**self.request.kwargs.copy())
E       TypeError: _open() got an unexpected keyword argument 'pilmode'
```

See #330

**Comment by adelavega** [comment]
It's actually Pillow complaining about `pilmode`, so my guess is that ImageIO doesn't catch it, and the kwarg gets passed down further than it should.

**Comment by tyarkoni** [comment]
The odd thing is that I couldn't find anyone else complaining about this, so it's possible there's some non-canonical usage in pliers. But may still be worth opening an issue on the imageio repo.

**Comment by adelavega** [comment]
Yeah, @rwblair and I couldn't either. I'll open an issue if I can't find any other explanation.

**Comment by adelavega** [comment]
Looks like despite imageio being set to the latest version in our requirements.txt, an older version was being installed. I think this is because `moviepy` was pinned to an older version. Upgrading `imageio` manually in the image fixed the issues. 

Looks like `imageio` was updated to accept `pilmode` in `v2.3.0` so that should be the minimum version in `requirements.txt`
