### ISSUE TITLE
docker image build failed locally

### ISSUE THREAD

**Issue by yarikoptic** [tyarkoni/pliers#347]
the check for being properly installed seems to fail
```
...
Step 7/8 : RUN python -m pliers.support.download
 ---> Running in 32a7381f92dd
/usr/local/bin/python: Error while finding module specification for 'pliers.support.download' (ModuleNotFoundError: No module named 'pliers.support')
The command '/bin/sh -c python -m pliers.support.download' returned a non-zero code: 1
$> git describe
0.2.3-174-g38e54d9
```

**Comment by yarikoptic** [comment]
ha -- I think it could be the effect of my restrictive mask (outside):
```
pliers@cd5e50a7ea71:/opt/pliers$ ls -ld pliers/
drwx------ 1 root root 270 May  9 15:16 pliers/
```
I now vaguely remember running into a similar situation.  I will augment Dockerfile by hardcoding `umask 022` within the installation `RUN`

**Comment by yarikoptic** [comment]
ah, `COPY . .` so it propagates my restrictive permissions.  Will augment by chmod after ;)  but also will cd away from that build directory when running the test

**Comment by kaczmarj** [comment]
I wonder if —chown=root in the COPY command would fix this too...

Jakub

**Comment by yarikoptic** [comment]
well, it is not about who owns (copy is owned by root) but rather who can read after you become another user (pliers) ;)  `chmod` worked for me, doing the final test build, will submit a PR

**Comment by adelavega** [comment]
@yarikoptic any idea if this got closed with a PR or still need it open?

**Comment by yarikoptic** [comment]
cannot test since now it fails with
```
$> docker build -t pliers-test-0.4.0-5-g3291840 .
...
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1) ...
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
The command '/bin/sh -c apt-get update -qq     && tmp_pkgs="cmake gcc g++ libc6-dev libgraphviz-dev libmagic-dev make"     && apt-get install -yq --no-install-recommends         ffmpeg         graphviz         libmagic1         tesseract-ocr         $tmp_pkgs     && pip install --no-cache-dir         --requirement requirements.txt         --requirement optional-dependencies.txt         ipython         notebook     && pip install --no-cache-dir --editable .     && python -m spacy download en_core_web_sm     && rm -rf ~/.cache/pip     && apt-get autoremove --purge -yq $tmp_pkgs     && apt-get clean     && rm -rf /var/lib/apt/lists/*     && useradd --no-user-group --create-home --shell /bin/bash pliers' returned a non-zero code: 1
```
;-)

**Comment by adelavega** [comment]
I think you have to run it from the main directory:
`docker build docker/ -t pliers`

**Comment by kaczmarj** [comment]
Running `docker build --file docker/Dockerfile .` from the top-level directory worked for me. Alternatively you could run this from the docker directory: `docker build ..`.

**Comment by adelavega** [comment]
Yep what @kaczmarj said :)

**Comment by adelavega** [comment]
Worked me for me too, btw

**Comment by yarikoptic** [comment]
> Alternatively you could run this from the docker directory: `docker build ..`.

that is what I have done... I will try now from the top directory

**Comment by adelavega** [comment]
Yes only the first method worked for me

**Comment by yarikoptic** [comment]
yeap -- only the first (less commonly used than the 2nd IMHO) method works!  I wonder if builds now work on docker hub or https://quay.io/?

**Comment by kaczmarj** [comment]
Sorry, the commands to build can be:

```
# Top-level directory
docker build -f docker/Dockerfile .
# docker directory
docker build -f Dockerfile  ..
```

Builds should work on dockerhub (haven't used quay but probably works too). Does pliers have an automated build set up?

**Comment by adelavega** [comment]
Okay, great. I'll close this issue. We could maybe add a note in the README, because I agree the command is a bit different than normal.

**Comment by adelavega** [comment]
Pliers doesn't have a dockerhub set up, to be semantically consistent @tyarkoni should set that up so its under his "domain"

**Comment by kaczmarj** [comment]
What do you think about moving the Dockerfile into the top-level directory? And then a note could be added to the main readme about how to build and run the image.

With the dockerfile in the top-level, users could run ‘docker build .’

**Comment by tyarkoni** [comment]
Probably it's past time for pliers to move to a different organization anyway, since it has so many contributors. I'll move it to psychoinformatics-lab.
