### ISSUE TITLE
Create pip install option for optional dependencies

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#356]
Currently installing from pip doesn't install all the optional dependencies in `optional-dependencies.txt`. It would be good to add an `'all'` option (or something more appropriately named) to `extras_require` in `setup.py` that allows users to `pip install pliers[all]`.

**Comment by adelavega** [comment]
This was closed with #358 and I'm updating it in 0.4.0. Should probably unify them formally in the future.
