### ISSUE TITLE
Librosa: Should details on argument specification point to specific feature site?

### ISSUE THREAD

**Issue by PeerHerholz** [tyarkoni/pliers#363]
The docstrings of the [Librosa feature extractors](https://github.com/tyarkoni/pliers/blob/master/pliers/extractors/audio.py) point to the [general feature side of the librosa documentation](https://librosa.github.io/librosa/feature.html), where not all features are documented (e.g., `onset_strength` is listed under [onset_detection](https://librosa.github.io/librosa/onset.html)). Should the docstrings therefore maybe be updated to point to the feature specific site in the librosa docs?

**Comment by adelavega** [comment]
@PeerHerholz just looking to clear up some old issue but if you want to update these doc strings that would be cool. Otherwise, I'll probably close it in soon.

**Comment by PeerHerholz** [comment]
Sure thing, on it! Sorry, didn't know if I should do the changes or not.
