### ISSUE TITLE
 add speechpy for speech processing and recognition

### ISSUE THREAD

**Issue by PeerHerholz** [tyarkoni/pliers#377]
Ahoi hoi everyone,

I just stumbled upon [SpeechPy](https://github.com/astorfi/speechpy) for speech processing and recognition. Should I/we evaluate the overlap with current pliers functionality and if suitable integrate it?

Best, Peer

**Comment by tyarkoni** [comment]
Sure, feel free. One minor concern is that while there are a lot of stars, actual usage seems to be pretty minimal (few issues/PRs). I'm not in a position to say if this is because the package is so well-written there are no bugs, or if the features it extracts are just not super useful...

**Comment by qmac** [comment]
Was there a particular feature that caught your eye? On my first glance it looks quite similar to the librosa set

**Comment by PeerHerholz** [comment]
Thanks for the replies!

Yeah, that was exactly my point regarding the overlap between SpeechPy and already supported functionality. I'll have a look and update asap.

**Comment by PeerHerholz** [comment]
I checked the available features and based on my understanding I would say that there's great overlap with the features already supported in pliers. Hence, if no one objects and/or thinks a certain feature would be suitable/needed to be integrated, I'm going to close this for now.
