### ISSUE TITLE
Drop vestigial Python 2 features

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#391]
We already officially only support and test Python 3, but we still have vestigial Py2 code all over the place (most notably, use of `six`). It's probably worth doing a sweep through the codebase and removing as much as possible of the Py2/3 compatibility code to reduce the maintenance burden.

See also: #323

**Comment by adelavega** [comment]
Probably worth also uniformly using pathlib as well

**Comment by hugovk** [comment]
Oops, looks like #393 overlaps with #392!

**Comment by tyarkoni** [comment]
@adelavega agreed, but that can be a separate PR.

**Comment by tyarkoni** [comment]
@hugovk I think we need to decide whether or not we're dropping 3.5 support. I incline not to unless we're already using 3.6+ features, which I don't think is the case.

It looks like the main difference between PRs, aside from programmatic changes via `pyupgrade`, is that I re-ordered import statements everywhere. Unless you have objections, I think I'll merge #392, and if we decide to limit to 3.6+, you can open a new PR for that. Sound reasonable?

**Comment by hugovk** [comment]
Yes, that's reasonable.

Dropping 3.5 is a separate conversation, distinct from this issue.

**Comment by tyarkoni** [comment]
Okay, I merged #392. You're welcome to open a PR with other `pyupgrade` changes I didn't make manually (e.g., updating `super()` calls) as long as they're 3.5 compatible. Thanks for the PR, and sorry about the confusion—I should have immediately self-assigned when I opened the issue.

**Comment by hugovk** [comment]
Thanks, I've rebased it into https://github.com/tyarkoni/pliers/pull/393 and dropped the commit to upgrade to 3.6+ syntax.

**Comment by tyarkoni** [comment]
Great, thanks! I'll merge as soon as the tests pass.
