### ISSUE TITLE
add sphinx support

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#4]

**Comment by ljchang** [comment]
@tyarkoni: I recently updated my documentation for nltools and found a couple of new things that I found very helpful.  First, if you're planning on using readthedocs again, there is a new [beta](http://read-the-docs.readthedocs.io/en/latest/conda.html) for using conda which works way better and you don't need to deal with Mock for all the packages that have c-libraries.  Second, [sphinx-gallery](https://github.com/sphinx-gallery/sphinx-gallery) is really helpful for making tutorials and it autobuilds jupyter notebooks to download.  I believe it's developed by the scikit-learn/nilearn team.  I should be able to help with this in a couple of weeks, but this has made things way easier for me.  I sort of dreaded dealing with this before.

**Comment by tyarkoni** [comment]
Thanks, I'll keep this in mind when I get back to this!

**Comment by qmac** [comment]
Closing after #228
