### ISSUE TITLE
Error using GoogleVisionAPIFaceExtractor

### ISSUE THREAD

**Issue by queenknight** [tyarkoni/pliers#403]
Hi! I'm new to coding and had an error trying out the GoogleVisionAPIFaceExtractor to identify the number of faces appearing each second on a 10min video. I had already set an environment variable for the API key.

**This is the code that I used:**

```
from pliers.stimuli import VideoStim
from pliers.filters import FrameSamplingFilter
from pliers.extractors import GoogleVisionAPIFaceExtractor, merge_results

video = VideoStim('/Users/queenknight/Documents/movie.mp4')
sampler = FrameSamplingFilter(hertz=1)
frames = sampler.transform(video)

ext = GoogleVisionAPIFaceExtractor()
results = ext.transform(frames)
df = merge_results(results, )

df.to_excel('moviegoogleface.xlsx', index=False, header=True)
```

**This was the error I got:**
```
638it [47:07,  4.43s/it]
Stim: 638it [00:00, 73165.80it/s]
Traceback (most recent call last):
  File "/Users/queenknight/PycharmProjects/Movie/Faceextractor_movie.py", line 13, in <module>
    df = merge_results(results, )
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/extractors/base.py", line 271, in merge_results
    dfs.append(r.to_df(timing=_timing, metadata=metadata,
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/extractors/base.py", line 114, in to_df
    df = self.extractor._to_df(self, **to_df_kwargs)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/extractors/api/google.py", line 80, in _to_df
    name = 'landmark_' + lm['type'] + '_%s'
KeyError: 'type'
```

**May I know if this is a bug or an error in my code? Would appreciate any solution to fix it, thank you!**
Unfortunately, I see that the Google Cloud Vision API recorded the number of my requests despite the error, eating into the free trial.

**Comment by tyarkoni** [comment]
@queenknight thanks for the report. I haven't had a chance to look into this yet, but my initial guess based on the error is that the Google face APIs may have changed the structure of the results it returns, potentially breaking our extractor classes. 

I should note that we're considering removing all of the remote API-based extractors in pliers, as they cost money and are very burdensome to maintain (because they change constantly). You could consider using the `FaceRecognitionFeatureExtractor`, which uses a pretrained model locally, so it's free and probably won't produce this error. We haven't done systematic benchmarking, but qualitatively, at least, results seem comparable.

**Comment by adelavega** [comment]
If you use the local face detection algorithm, use the `cnn` model for better accuracy:
e.g.
`face_ext = FaceRecognitionFaceLocationsExtractor(model='cnn')`

**Comment by adelavega** [comment]
@queenknight I just tried using Clarifai and it worked for me.

According to the docs, we should specify `CLARIFAI_API_KEY` not `CLARIFAI_APP_ID` and `CLARIFAI_APP_SECRET`.

I think we made this update a while back. You should be able to get the CLARIFAI_API_KEY from Clarifai here: https://portal.clarifai.com/settings/authentication

Let me know if I missed some outdated docs that ask for a id and secret key pair.

**Comment by queenknight** [comment]
@adelavega Oh my I see!

Here's what I did: 
1. Copy personal access token on [https://portal.clarifai.com/settings/authentication](url)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/67893148/87734155-68afd680-c804-11ea-8557-10b1d6879dba.png">
2. In pycharm, edit configuration:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/67893148/87733581-cd6a3180-c802-11ea-9e68-57efa597e693.png">
3. Ran the code:

`from pliers.stimuli import VideoStim
from pliers.extractors import ClarifaiAPIVideoExtractor, merge_results

video = VideoStim('/Users/queenknight/video123.mp4')

ext = ClarifaiAPIVideoExtractor()
results = ext.transform(video)
df = merge_results(results, )

df.to_excel('reunion_clarifai_videotag.xlsx', index=False, header=True)`

4. Received error:

`WARNING:root:b'GET https://api.clarifai.com/v2/models FAILED(1594943295.694556). status_code: 401, reason: Unauthorized, error_code: 11008, error_description: Invalid API key or Invalid API key/application pair, error_details: Must provide app external ID in API authorizer\n >> Python client 2.6.2 with Python 3.8.3 on darwin\n >> GET https://api.clarifai.com/v2/models\n >> REQUEST(1594943295.694556) {\n  "page": 1,\n  "per_page": 20\n}\n >> RESPONSE(1594943295.694556) {\n  "status": {\n    "code": 11008,\n    "description": "Invalid API key or Invalid API key/application pair",\n    "details": "Must provide app external ID in API authorizer",\n    "req_id": "b09e14c822ac4f27865fca4ad00fe3a0"\n  },\n  "models": []\n}'

Traceback (most recent call last):
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-81dab65605e1>", line 3, in <module>
    runfile('/Users/queenknight/PycharmProjects/Movie/Clarifai_movie.py', wdir='/Users/queenkight/Library/Application Support/JetBrains/PyCharmCE2020.1/scratches')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/queenknight/PycharmProjects/Movie/Clarifai_movie.py", line 7, in <module>
    results = ext.transform(video)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/extractors/base.py", line 17, in transform
    result = super(Extractor, self).transform(stim, *args, **kwargs)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/transformers/base.py", line 56, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/transformers/base.py", line 129, in transform
    result = self._transform(validated_stim, *args, **kwargs)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/transformers/api/base.py", line 44, in _transform
    return super(APITransformer, self)._transform(stim, *args, **kwargs)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/extractors/base.py", line 25, in _transform
    return self._extract(stim, *args, **kwargs)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/extractors/api/clarifai.py", line 169, in _extract
    outputs = self._query_api(vids)
  File "/Users/queenknight/OneDrive/EDX/lib/python3.8/site-packages/pliers/extractors/api/clarifai.py", line 95, in _query_api
    tags = self.model.predict(objects, model_output_info=model_output_info)
AttributeError: 'NoneType' object has no attribute 'predict'
`

I get something similar when I use ClarifaiAPIImageExtractor too.. Do you think it is a problem with my API key? 

Thank you very much for your time!

**Comment by adelavega** [comment]
Hey, so first of all, I'm definitely getting a weird result from `ClarifaiAPIVideoExtractor` so let's avoid that one for now. 
(BTW, I deleted your screen shot bc the API key is sensitive, so don't post that publicly)

`ClarifaiAPIImageExtractor` works for me. It's possible that the API key is not being read-in. 
If you pass a video to that extractor, pliers will automatically re-sample the video to 

You could add the following to your code, and you should see your API key printed. If not, then that's the problem. 

```
import os
print(os.environ['CLARIFAI_API_KEY'])
```

If there is a different error, let me know

**Comment by queenknight** [comment]
Really weird indeed!

I tried troubleshooting further (I think there was problem reading the API key), while the personal access token still did not work for me, it finally worked with the app specific API key! 

Thank you so much for your help :)
