### ISSUE TITLE
Wishlist: Movie frame cropping before content labeling

### ISSUE THREAD

**Issue by mih** [tyarkoni/pliers#79]
While exporing the Google vision API I found that it makes a big difference if movie frames are cropped (freed of any horizontal bars) before labeling. Without cropping they get "Screenshot" labels, but after cropping more of the actual content is tagged.

**Comment by tyarkoni** [comment]
This would be great to add as a new `FrameCroppingFilter`. Do you have a pre-baked snippet for cropping images?

**Comment by mih** [comment]
So far I have used http://pillow.readthedocs.io/en/3.4.x/reference/Image.html#PIL.Image.Image.crop for actual images.

In case of a motion picture with bars the bounding box for cropping would be always constant, hence could be pre-configured.

I am not yet familiar with the data structures that a filter would operate on, but even if it is just pixel arrays, cropping a rectangular area should be a slicing operation.
