### ISSUE TITLE
Add multi-step Converters

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/pliers#83]
To really unlock the potential of the graph API, we need to support implicit conversion between `Stim` types that involve multiple steps--e.g., `VideoStim` to `ComplexTextStim` via an extracted `AudioStim`. There are (at least) two ways we could go about this:

1. Recursively try to construct valid paths from the input `Stim` to the output `Stim`, and stop as soon as one is found. E.g., suppose we pass a `VideoStim` to a `TextExtractor`. Then `get_converter` would search all possible paths from `VideoStim` to `TextStim` until it found `VideoStim` --> `AudioStim` --> `ComplexTextStim`.
2. Manually add `Converter` classes for all valid paths, which explicitly call the full chain internally. E.g., we would write a new `VideoToComplexTextStimConverter` with a `_convert` method that explicitly uses a `VideoToAudioConverter` class, then an `AudioToTextConverter`.

In principle, (1) is the cleaner and more extensible approach. But it introduces completely unnecessary computation when the number of valid paths between Stims is small (as it currently is). The main disadvantage of (2) is if we add many more `Stim` types, we could end up with combinatorial explosion.

I guess for now I favor (2), and if it starts to get unwieldy, we can move to (1).

This is a high-priority issue that we should try to get done before revamping the README, because it would be nice to be able to show a `Graph` example where the user only has to worry about the leaf nodes (all of which are Extractors), and doesn't have to explicitly think about the Converters.

**Comment by qmac** [comment]
To reiterate an issue brought up in past discussions: how do we resolve ambiguities? E.g. another valid path for `VideoToComplexTextStimConverter` would be `VideoStim` --> `ImageStim`(s) --> `TextStim`(s) if the user wants visual text instead of audio text. Do we make implicit assumptions based on common use cases?

**Comment by tyarkoni** [comment]
Thanks for bringing that up, I forgot about that. I think that argues in favor of option (2) above, since it allows us to easily parameterize the possible paths in an initializer argument (and set a sensible default). So, for example, for `VideoToComplexTextStimConverter`, we could have a signature like:

```python

class VideoToComplexTextStimConverter(Converter):

    def __init__(self, via='audio'):
        pass
```

...where the `via` argument could be set to either 'audio' or 'image', and then when `convert()` is called, we explicitly route through the desired path. This could also be easily extended to support lists for more complex routing.

**Comment by tyarkoni** [comment]
Closing, as this is now supported. Most of the work was handled by @qmac in #96, which became my #99 due to my inability to think ahead more than one PR.
