### ISSUE TITLE
Should implicit conversion output CollectionStimMixins?

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#87]
Say we are passing an `AudioStim` through a `LengthExtractor`, which takes `TextStim` inputs. The implicit conversion will look for converters that go audio->text. However, most of the converters will instead have `AudioStim`->`ComplexTextStim` specified. 

Should the implicit conversion also look for conversions to collection stimuli who's elements are of `LengthExtractor`'s input type? Either way it may be a good idea to put an `element_type` specification in all `CollectionStimMixin`s. 

Alternatively, which we coincidentally have implemented now, we could just have converters specify `AudioStim`->`TextStim`, (even though they actually output `ComplexTextStim`) and have the logic in `transformers.py` take over from there.

**Comment by tyarkoni** [comment]
Hmm... good question. I guess my assumption would be that if you're trying to apply a text extractor to an `AudioStim`, you probably want to loop over extracted words. So we would want to pass a `ComplexTextStim`. The only issue with that is that is that `ComplexTextStim` doesn't actually inherit from `TextStim`. If it did, I think the `LengthExtractor` would work just fine, via the `transformers.py` logic you mention. Is there any downside to changing the inheritance to work that way? There might be a good reason why it's not set up that way, I don't remember...

**Comment by tyarkoni** [comment]
Closing this since I think we already implement @qmac's option (2) above. It's not perfect, as it's not ideal to say the `Converter` returns a `TextStim` when it actually returns a `ComplexTextStim`, but I think we can live with this for now and revisit in future if it becomes a problem.
