### ISSUE TITLE
Google API test fail with cryptography>1.4

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#93]
With package cryptography greater than 1.5, the Google API tests fail with error:
`TypeError: cannot instantiate ctype 'EVP_MD_CTX' of unknown size`

Google leads to this: https://github.com/burnash/gspread/issues/407

Which suggests that the package recently changed. Downgrading to 1.4 fixed the issue for me and all tests passed.

**Comment by tyarkoni** [comment]
Okay, I'll pin that version in requirements for now. Will leave this open so we can reevaluate in a couple of months and see if it's been fixed.
